name: Grant Scraper Scheduled Run

on:
  schedule:
    # runs once a week on sunday at 12:00 AM UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:  
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > scraper/.env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_API_KEY }}" >> scraper/.env

      - name: Run scrapers
        run: |
          cd scraper
          mkdir -p logs data
          python run_all_scrapers.py

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs
          path: scraper/logs/scraper_run.log
          if-no-files-found: warn
          retention-days: 30

      - name: Archive grant data
        uses: actions/upload-artifact@v4
        with:
          name: grant-data
          path: |
            scraper/data/all_grants.json
            scraper/data/all_grants.csv
          if-no-files-found: warn
          retention-days: 30
