name: Grant Scraper Scheduled Run

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python3-distutils (for Python 3.11+)
        run: sudo apt-get update && sudo apt-get install -y python3-distutils

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > scraper/.env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_API_KEY }}" >> scraper/.env

      - name: Run scrapers
        run: |
          cd scraper
          mkdir -p logs data
          python run_all_scrapers.py

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs
          path: scraper/logs/scraper_run.log
          if-no-files-found: warn
          retention-days: 30

      - name: Archive grant data
        uses: actions/upload-artifact@v4
        with:
          name: grant-data
          path: |
            scraper/data/all_grants.json
            scraper/data/all_grants.csv
          if-no-files-found: warn
          retention-days: 30