name: Grant Scraper Scheduled Run

on:
  schedule:
    # Run once a week on Sunday at 12:00 AM UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_API_KEY }}" >> .env

      - name: Run scrapers
        run: python run_all_scrapers.py

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: scraper-logs
          path: logs/scraper_run.log
          retention-days: 30

      - name: Archive grant data
        uses: actions/upload-artifact@v3
        with:
          name: grant-data
          path: |
            data/all_grants.json
            data/all_grants.csv
          retention-days: 30 
