name: Deploy to Vercel on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optional: set environment variables on Vercel
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: fundhomecarescraper
          envVariableKeys: SUPABASE_URL,SUPABASE_API_KEY
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          TARGET_SUPABASE_URL: preview,development,production
          TYPE_SUPABASE_URL: encrypted

          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          TARGET_SUPABASE_API_KEY: preview,development,production
          TYPE_SUPABASE_API_KEY: encrypted

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}